config/routes.rb
resources :issues, only: [] do
  resources :staff_ratings, only: :new
end
resources :users, only: [] do
  resources :staff_ratings, only: :new
end
resources :projects, only: [] do
  resources :staff_ratings, only: :index
end
resources :staff_ratings

app/models/rating.rb
class Rating < ActiveRecord::Base
  include Redmine::SafeAttributes

  unloadable

  self.table_name = 'centos_ratings'   

  safe_attributes 'mark', 'comments', 'evaluated_id', 'evaluator_id', 'issue_id', 'project_id'

  belongs_to :evaluated, class_name: 'User'
  belongs_to :evaluator, class_name: 'User'
  belongs_to :issue
  belongs_to :project

  validates_presence_of :evaluated, :evaluator
  validates :mark, inclusion: { in: 1..5 }, allow_blank: false

  acts_as_event title: proc{ |r| "#{r.evaluator.login} -> #{r.evaluated.login}#{ r.issue ? " (#{r.issue.subject})" : '' }: #{r.mark}" },
                description: :comments, 
                author: :evaluator, 
                url: proc{ |r| { controller: 'ratings', action: 'show', id: r.id } }

  acts_as_activity_provider find_options: { include: [:project] },
                            author_key: :evaluator_id

  before_validation :set_project

  def editable_by?( user )
    user == evaluator || user.admin?
  end

  def self.issue_rating( issue, user )
    where( evaluator_id: user.id, issue_id: issue.id ).first
  end

  def self.find_or_initialize_by(attributes, &block)
    where(attributes).first || new(attributes, &block)
  end

  private
  
  def set_project
    self.project_id = issue.project_id if project_id.nil? && !issue_id.nil?
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :find_rating, except: [:index, :new, :create]
  before_filter :build_rating_from_params, only: [:create, :update]
  before_filter :set_project, except: [:new, :index]
  before_filter :authorize,   except: [:new, :index]
  before_filter :check_editability, only: [:edit, :update, :destroy]


  helper :sort
  include SortHelper
  helper :queries
  include QueriesHelper


  def index
    @project = Project.find params[:project_id]
    @query = RatingQuery.build_from_params params, project: @project, name: '_'

    sort_init(@query.sort_criteria.empty? ? [['created_on', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    scope = @query.results_scope(order: sort_clause).
      includes(:project, :evaluated, :evaluator, :issue).
      preload(issue: [:project, :tracker, :status, :assigned_to, :priority])

    @entry_count = scope.count
    @entry_pages = Paginator.new @entry_count, per_page_option, params['page']
    @entries = scope.offset(@entry_pages.offset).limit(@entry_pages.per_page).all

    @average_mark = scope.average :mark
  end
  
  def show
  end

  def new
    @rating = User.current.centos_evaluations.build
    unless params[:issue_id].blank?
      @rating.issue = Issue.find params[:issue_id]
      @project, @rating.project = @rating.issue.project
    end
    @rating.evaluated = User.find params[:user_id] unless params[:user_id].blank?
    authorize
    render :form
  end

  def edit
    render :form
  end

  def update
    save_rating :edit
  end

  def create
    save_rating :new
  end

  def destroy
    @rating.destroy
    if @rating.issue
      redirect_to issue_path @rating.issue
    else
      redirect_to user_path @rating.evaluated
    end
  end

  protected

  def save_rating(fail_render)
    if @rating.save
      redirect_to rating_path @rating
    else
      render status: 422, action: fail_render
    end
  end

  def build_rating_from_params
    @rating = User.current.centos_evaluations.build if @rating.nil?
    @rating.safe_attributes = params[:rating]
  end

  def find_rating
    @rating = Rating.find params[:id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def set_project
    @project = @rating.issue.project
  end

  def authorize
    super params[:controller], params[:action], global = true
  end

  def check_editability
    render_403 unless @rating.editable_by?( User.current )
  end
end

app/views/ratings/index.html.slim
h2 = l :label_rating_plural

= form_tag({ controller: 'ratings', action: 'index', project_id: @project }, method: :get, id: 'query_form')

  #query_form_with_buttons.hide-when-print
    #query_form_content
      
      fieldset#filters class="collapsible #{ @query.new_record? ? '' : 'collapsed' }"
        legend onclick='toggleFieldset(this);' = l :label_filter_plural
        div style="#{ @query.new_record? ? '' : 'display: none;' }"
          = render partial: 'queries/filters', locals: { query: @query }
      
      fieldset.collapsible.collapsed
        legend onclick='toggleFieldset(this);' = l :label_options
        div style='display: none;'
          table
            tr
              td = l(:field_column_names)
              td = render_query_columns_selection(@query)


    p.buttons
      = link_to_function l(:button_apply), 'submit_query_form("query_form")', class: 'icon icon-checked'
      = link_to l(:button_clear), {project_id: @project, issue_id: @issue}, class: 'icon icon-reload'

- unless @entries.empty?
  .total-hours
    p #{ l :label_average_mark }: #{ html_hours @average_mark.round(2).to_s }

  = form_tag
    = hidden_field_tag 'back_url', url_for(params)
    .autoscroll
      table.list
        thead
          tr
            th.checkbox
              = link_to image_tag('toggle_check.png'),
                {},
                onclick: 'toggleIssuesSelection(this); return false;',
                title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}"

            - @query.inline_columns.each do |column|
              = column_header column
            th
        tbody
          - @entries.each do |entry|
            tr class="#{ cycle("odd", "even") } hascontextmenu"
              td.checkbox = check_box_tag("ids[]", entry.id, false, :id => nil)
              = raw @query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, entry)}</td>"}.join
              td.buttons
                - if entry.editable_by?( User.current )
                  = link_to image_tag('edit.png'), edit_rating_path(entry), title: l(:button_edit)
                  = link_to image_tag('delete.png'), rating_path(entry),
                                                       data: { confirm: l(:text_are_you_sure) },
                                                       method: :delete,
                                                       title: l(:button_delete)

= context_menu time_entries_context_menu_path

p.pagination = pagination_links_full @entry_pages, @entry_count

app/views/ratings/new.html.slim
= title l :label_centos_rating

= labelled_form_for @rating,
                    url: ratings_path,
                    html: { id: 'centos-rating-form' } do |f|

  = error_messages_for @rating

  .box.tabular
    .all_attributes
      = labelled_fields_for :rating, @rating do |f|
        - if @rating.issue
          p
            = f.hidden_field :issue_id
            = f.hidden_field :project_id
            label = l :label_issue
            span = @rating.issue.subject
        
        p
          = f.hidden_field :evaluated_id
          label = l :label_evaluated
          span = @rating.evaluated.login

        p = f.select :mark, 1..3, include_blank: true, required: true
        p = f.text_area :comments, rows: 5

  = submit_tag l :button_rate

app/views/ratings/show.html.slim
= title l :label_rating

.box.tabular
  p
    label = l :label_evaluator
    span = link_to @rating.evaluator.login, user_path(@rating.evaluator)

  - if @rating.issue
    p
      label = l :label_project
      = link_to @rating.project.name, project_path(@rating.project)

    p
      label = l :label_issue
      = link_to @rating.issue.subject, issue_path(@rating.issue)

  p
    label = l :label_evaluated
    span = link_to @rating.evaluated.login, user_path(@rating.evaluated)
  p
    label = l :field_mark
    span = @rating.mark
  p
    label = l :field_comments
    span = @rating.comments

.buttons
  - if @rating.editable_by?( User.current )
    = link_to image_tag('edit.png'), edit_rating_path(@rating), title: l(:button_edit)
    = link_to image_tag('delete.png'), rating_path(@rating),
                                         data: { confirm: l(:text_are_you_sure) },
                                         method: :delete,
                                         title: l(:button_delete)