config/routes.rb
resources :issues, only: [] do
  resources :staff_ratings, only: :new
end
resources :users, only: [] do
  resources :staff_ratings, only: :new
end
resources :projects, only: [] do
  resources :staff_ratings, only: :index
end
resources :staff_ratings

app/models/rating.rb
class Rating < ActiveRecord::Base
  include Redmine::SafeAttributes

  unloadable

  self.table_name = 'centos_ratings'   

  safe_attributes 'mark', 'comments', 'evaluated_id', 'evaluator_id', 'issue_id', 'project_id'

  belongs_to :evaluated, class_name: 'User'
  belongs_to :evaluator, class_name: 'User'
  belongs_to :issue
  belongs_to :project

  validates_presence_of :evaluated, :evaluator
  validates :mark, inclusion: { in: 1..5 }, allow_blank: false

  acts_as_event title: proc{ |r| "#{r.evaluator.login} -> #{r.evaluated.login}#{ r.issue ? " (#{r.issue.subject})" : '' }: #{r.mark}" },
                description: :comments, 
                author: :evaluator, 
                url: proc{ |r| { controller: 'ratings', action: 'show', id: r.id } }

  acts_as_activity_provider find_options: { include: [:project] },
                            author_key: :evaluator_id

  before_validation :set_project

  def editable_by?( user )
    user == evaluator || user.admin?
  end

  def self.issue_rating( issue, user )
    where( evaluator_id: user.id, issue_id: issue.id ).first
  end

  def self.find_or_initialize_by(attributes, &block)
    where(attributes).first || new(attributes, &block)
  end

  private
  
  def set_project
    self.project_id = issue.project_id if project_id.nil? && !issue_id.nil?
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :find_rating, except: [:index, :new, :create]
  before_filter :build_rating_from_params, only: [:create, :update]
  before_filter :set_project, except: [:new, :index]
  before_filter :authorize,   except: [:new, :index]
  before_filter :check_editability, only: [:edit, :update, :destroy]


  helper :sort
  include SortHelper
  helper :queries
  include QueriesHelper


  def index
    @project = Project.find params[:project_id]
    @query = RatingQuery.build_from_params params, project: @project, name: '_'

    sort_init(@query.sort_criteria.empty? ? [['created_on', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    scope = @query.results_scope(order: sort_clause).
      includes(:project, :evaluated, :evaluator, :issue).
      preload(issue: [:project, :tracker, :status, :assigned_to, :priority])

    @entry_count = scope.count
    @entry_pages = Paginator.new @entry_count, per_page_option, params['page']
    @entries = scope.offset(@entry_pages.offset).limit(@entry_pages.per_page).all

    @average_mark = scope.average :mark
  end
  
  def show
  end

  def new
    @rating = User.current.centos_evaluations.build
    unless params[:issue_id].blank?
      @rating.issue = Issue.find params[:issue_id]
      @project, @rating.project = @rating.issue.project
    end
    @rating.evaluated = User.find params[:user_id] unless params[:user_id].blank?
    authorize
    render :form
  end

  def edit
    render :form
  end

  def update
    save_rating :edit
  end

  def create
    save_rating :new
  end

  def destroy
    @rating.destroy
    if @rating.issue
      redirect_to issue_path @rating.issue
    else
      redirect_to user_path @rating.evaluated
    end
  end

  protected

  def save_rating(fail_render)
    if @rating.save
      redirect_to rating_path @rating
    else
      render status: 422, action: fail_render
    end
  end

  def build_rating_from_params
    @rating = User.current.centos_evaluations.build if @rating.nil?
    @rating.safe_attributes = params[:rating]
  end

  def find_rating
    @rating = Rating.find params[:id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def set_project
    @project = @rating.issue.project
  end

  def authorize
    super params[:controller], params[:action], global = true
  end

  def check_editability
    render_403 unless @rating.editable_by?( User.current )
  end
end

app/views/centos/rating/issues/_form.html.slim
- if User.current.allowed_to?(:centos_rate, @project)

  - rating = StaffRating.issue_rating issue, User.current

  fieldset
    legend = l :label_rating
    p
      label = l :label_evaluated
      = select_tag 'issue[rating[evaluated_id]]', \
                    options_for_select((@project.users_available_to :centos_be_rated).collect { |u| [u.name, u.id] }, \
                                        rating.try(:evaluated_id)), include_blank: true
    p
      label = l :field_mark
      = select_tag 'issue[rating[mark]]', options_for_select(1..5, rating.try(:mark)), include_blank: true
    p
      label = l :field_comments
      = text_field_tag 'issue[rating[comments]]', rating.try(:comments), size: 104

app/views/centos/rating/issues/_rate.html.slim
- if User.current.allowed_to?(:centos_rate, @project)

  - ratings = issue.ratings
  
  tr
    th
    td
    th = "#{l :label_rating_plural}:"
    td
      - if ratings.empty?
        = link_to l(:button_rate), new_issue_staff_rating_path(issue)
      - else
        p
          - ratings.group_by(&:evaluated).each do |evaluated, items|
            - average_mark = items.size == 0 ? 0 : (items.inject(0) {|sum, el| sum + el.mark}.to_f / items.size)
            strong = "#{evaluated}: #{average_mark.round(2)}"
            br